- name: Delete Rosa Cluster
  debug:
    msg: Deleting cluster  -> '{{ clustername }}'

- name: Check ROSA plugin exist
  ansible.builtin.command: rosa version
  register: plugin_exist

- debug : msg="{{ plugin_exist.stdout }}"
  failed_when: plugin_exist.rc != 0

- name: Check AWS Cluster
  ansible.builtin.command: rosa describe cluster --cluster={{ clustername }} -o json
  register: check_cluster
  no_log: true
  ignore_errors: true

- name: Check Cluster JSON 
  debug:
    msg: "{{ check_cluster.state | from_json | community.general.json_query('state') }}" 


# - name: Check Cluster Status via JSON
#   set_fact:
#        interfaces: "{{ (check_cluster.stdout | from_json).state }}" 
       #interfaces: (check_cluster.stdout | from_json).state
       #interfaces: "{{ check_cluster.state }}"

# - name: Print interfaces 
#   debug:
#     var: "{{ interfaces }}"  
    

# - ansible.builtin.assert:
#     that:
#       - check_cluster.rc == 0
#     fail_msg: "The Cluster {{ clustername }} does not exist!"
#     success_msg: "The Cluster {{ clustername }} exists!"
  
# - name: Delete AWS Cluster
#   ansible.builtin.command: rosa delete cluster --cluster={{ clustername }} --watch --yes
#   register: delete_cluster_stdout
#   when: check_cluster.rc == 0

# - debug: msg="{{ delete_cluster_stdout.stdout }}"